/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef VPNTEST_PRIVATE_H
#define VPNTEST_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.11.7.17"
#define VER_MAJOR	1
#define VER_MINOR	11
#define VER_RELEASE	7
#define VER_BUILD	17
#define COMPANY_NAME	"MBSinc"
#define FILE_VERSION	"1.11.7.17"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	"UMBRELLA-VPN"
#define LEGAL_COPYRIGHT	"©2017 Bagus Saputra"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"UMBRELLA-VPN"
#define PRODUCT_NAME	"UMBRELLA-VPN"
#define PRODUCT_VERSION	"1.11.7.17"

#endif /*VPNTEST_PRIVATE_H*/
